# This is a basic workflow to help you get started with Actions

name: CI (redis-timeseries)

on:
  push:
    branches: [ master ]
    tags:
      - 'redis_timeseries/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  redis-timeseries:

    strategy:
      matrix:
        arch: [armv7]
        distro: [bulleyes, bookworn]

    runs-on: ubuntu-latest

    name: redis-timeseries ${{ matrix.arch }} / ${{ matrix.distro }} 

    steps:
      - uses: actions/checkout@v2

      - name: Set tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build RedisTimeSeries (on arm)
        id: build-redis-timeseries
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          githubToken: ${{ github.token }}

          install: |
            apt-get update -q -y
            apt-get install -q -y wget jq curl git build-essential openssl libssl-dev python3 python3-dev autoconf libtool m4 automake

          run: |
            ./build.sh redis_timeseries ${{ matrix.arch }} ${{ steps.vars.outputs.tag }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: redis_timeseries-*.gz

