# This is a basic workflow to help you get started with Actions

name: CI (redis)

on:
  push:
    branches: [ master ]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  redis:

    strategy:
      matrix:
        arch: [armv7]
        distro: [bookworm, bullseye]

    runs-on: ubuntu-latest

    name: ${{ matrix.arch }} / ${{ matrix.distro }} 

    steps:
      - uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v2
        name: Build redis (on arm)
        id: build-redis
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          githubToken: ${{ github.token }}

          install: |
            apt-get update -q -y
            apt-get install -q -y wget jq curl git build-essential openssl libssl-dev libsystemd-dev

          run: |
            ./build.sh ${{ matrix.arch }} ${{ matrix.distro }} ${{ github.ref_name }} 

      - uses: actions/upload-artifact@v4
        with:
          name: redis-${{ matrix.arch }}-${{ matrix.distro }}-${{ github.ref_name }}
          path: redis-*.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: redis-*.gz

